spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_borrowing_system?createDatabaseIfNotExist=true
    username: root
    password: 1234

server:
  port: 8082

jpa:
  hibernate:
    ddl-auto: update
  show_sql: true